version: '3.8'
services:
  api:
    image: node:20.19.4
    container_name: donations_api
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - database
    ports:
     - ${API_PORT}:3001
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: donations_db
      MYSQL_PORT: ${MYSQL_PORT}
      NODE_ENV: ${NODE_ENV}
    command: npm run start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    
  database:
    image: mysql:9.4.0
    platform: linux/amd64
    container_name: donations_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    